let allBookings=[];
const $=id=>document.getElementById(id);
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
async function boot(){const me=await api("/api/admin/me"); if(me.loggedIn) showApp();}
function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");loadAll();loadUpdates();}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({username:$("username").value,password:$("password").value})});showApp()}catch(x){$("loginError").textContent=x.message}});
$("logout").onclick=async()=>{await api("/api/admin/logout",{method:"POST"});location.reload()};
$("filter").onchange=render;$("search").oninput=render;
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const isOrders=btn.dataset.tab==="orders";$("ordersTab").classList.toggle("hidden",!isOrders);$("updatesTab").classList.toggle("hidden",isOrders);if(!isOrders)loadUpdates()}));
async function loadAll(){try{const [stats,rows]=await Promise.all([api("/api/admin/stats"),api("/api/admin/bookings")]);$("total").textContent=stats.total;$("newCount").textContent=stats.NEW;$("processing").textContent=stats.PROCESSING;$("completed").textContent=stats.COMPLETED;$("cancelled").textContent=stats.CANCELLED;allBookings=rows;render()}catch(e){alert(e.message)}}
function render(){const q=$("search").value.toLowerCase(), f=$("filter").value;const rows=allBookings.filter(b=>(f==="ALL"||b.status===f)&&(!q||[b.booking_id,b.name,b.phone,b.service].join(" ").toLowerCase().includes(q)));$("rows").innerHTML=rows.map(b=>`<tr><td><b>${esc(b.booking_id)}</b></td><td>${esc(b.name)}<br><a href="tel:${esc(b.phone)}">${esc(b.phone)}</a></td><td>${esc(b.service)}</td><td>${esc(b.pickup_date)}<br><small>${esc(b.time||"")}</small></td><td><span class="pill ${b.status.toLowerCase()}">${b.status}</span></td><td>${fmt(b.created_at)}</td><td><button class="view" onclick="openDetail('${esc(b.booking_id)}')">View</button></td></tr>`).join("");$("empty").classList.toggle("hidden",!rows.length)}
async function openDetail(id){try{const b=await api("/api/admin/bookings/"+encodeURIComponent(id));$("detailBody").innerHTML=`<p class="eyebrow">BOOKING DETAILS</p><h2>${esc(b.booking_id)}</h2><div class="detail-grid"><div><small>Customer</small><b>${esc(b.name)}</b></div><div><small>Mobile</small><b><a href="tel:${esc(b.phone)}">${esc(b.phone)}</a></b></div><div><small>Service</small><b>${esc(b.service)}</b></div><div><small>Pickup / Delivery</small><b>${esc(b.mode)}</b></div><div><small>Preferred date</small><b>${esc(b.pickup_date)}</b></div><div><small>Time</small><b>${esc(b.time||"—")}</b></div></div><div class="address"><small>Address</small><p>${esc(b.address)}</p></div><div class="address"><small>Notes</small><p>${esc(b.notes||"—")}</p></div><div class="photos">${(b.photos||[]).map(p=>`<a href="${p.url}" target="_blank"><img src="${p.url}" alt="Booking photo"></a>`).join("")}</div><label class="status-label">Update status<select id="statusSelect"><option>NEW</option><option>PROCESSING</option><option>COMPLETED</option><option>CANCELLED</option></select></label><button class="btn primary full" onclick="saveStatus('${esc(b.booking_id)}')">Save Status</button><a class="btn wa full" target="_blank" href="https://wa.me/91${encodeURIComponent(b.phone)}?text=${encodeURIComponent(waMsg({...b,status:$("statusSelect")?.value||b.status}))}">WhatsApp Customer</a><p class="muted">Status is saved in the database. WhatsApp opens a ready-to-send message; you control sending it.</p>`;$("statusSelect").value=b.status;$('detail').classList.remove('hidden')}catch(e){alert(e.message)}}
function waMsg(b){const label={NEW:"received",PROCESSING:"now being processed",COMPLETED:"completed",CANCELLED:"cancelled"}[b.status]||b.status.toLowerCase();return `Hi ${b.name},\n\nYour Rudhra Bags & Footwears service booking ${b.booking_id} is ${label}.\nService: ${b.service}\nPreferred date: ${b.pickup_date}\n\nThank you.`}
async function saveStatus(id){const status=$("statusSelect").value;try{await api("/api/admin/bookings/"+encodeURIComponent(id)+"/status",{method:"PATCH",body:JSON.stringify({status})});closeDetail();await loadAll()}catch(e){alert(e.message)}}
function closeDetail(){$("detail").classList.add("hidden")}
function fmt(s){try{return new Date(s).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}catch{return s}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}

async function loadUpdates(){try{const rows=await api("/api/admin/updates");const box=$("updateList");if(!rows.length){box.innerHTML='<div class="empty">No updates yet.</div>';return}box.innerHTML=rows.map(u=>`<article class="admin-update ${u.active?'is-active':'is-off'}"><div><span class="update-type">${esc(u.type)}</span><h3>${esc(u.title)}</h3><p>${esc(u.message)}</p><small>${fmt(u.created_at)}</small></div><div class="post-actions"><span class="pill ${u.active?'published':'draft'}">${u.active?'LIVE':'HIDDEN'}</span><button class="view" onclick="toggleUpdate(${u.id},${u.active?0:1})">${u.active?'Hide':'Publish'}</button><button class="danger" onclick="deleteUpdate(${u.id})">Delete</button></div></article>`).join("")}catch(e){alert(e.message)}}
$("updateForm").addEventListener("submit",async e=>{e.preventDefault();$("updateMsg").textContent="";try{await api("/api/admin/updates",{method:"POST",body:JSON.stringify({type:$("updateType").value,title:$("updateTitle").value,message:$("updateMessage").value})});$("updateForm").reset();$("updateMsg").textContent="Update published successfully.";loadUpdates()}catch(e){$("updateMsg").textContent=e.message}});
async function toggleUpdate(id,active){try{await api("/api/admin/updates/"+id,{method:"PATCH",body:JSON.stringify({active})});loadUpdates()}catch(e){alert(e.message)}}
async function deleteUpdate(id){if(!confirm("Delete this update?"))return;try{await api("/api/admin/updates/"+id,{method:"DELETE"});loadUpdates()}catch(e){alert(e.message)}}
boot();
